server:
  port: 8000

spring:
  application:
    name: school-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true  #是否与服务注册于发现组件结合，通过 serviceId 转发到具体的服务
          lower-case-service-id: true
      routes:
        - id: gateway-consumer
          uri: lb://wzcprovider
          #uri: http://127.0.0.1:9002  #两种方法均可
          predicates:
            - Path=/clients/**